# DC schema

# --- !Ups


CREATE TABLE T_APP (
  ID integer NOT NULL AUTO_INCREMENT PRIMARY KEY,
  C_APPID VARCHAR(45) NULL,
  C_APPNAME VARCHAR(45) NULL,
  C_APPDESC VARCHAR(200) NULL,
  C_APPTYPE VARCHAR(45) NULL,
  C_CONTAINER VARCHAR(45) NULL,
  C_DEPTYPE VARCHAR(45) NULL,
  C_PROJMGR VARCHAR(45) NULL,
  C_PROCESSNAME VARCHAR(45) NULL,
  C_TEAM       VARCHAR(45) NULL,
  C_APPREPO   VARCHAR (45) NULL,
  C_PLAYBOOK  VARCHAR(500) NULL

);


CREATE TABLE T_USERS (
  ID integer NOT NULL AUTO_INCREMENT PRIMARY KEY,
  USER_ID VARCHAR(45) NULL,
  USER_FIRST_NAME VARCHAR(45) NULL,
  USER_LAST_NAME VARCHAR(200) NULL,
  USER_MGR_NAME VARCHAR(45) NULL,
  USER_PROC_NAME VARCHAR(45) NULL,
  USER_TEAM_NAME VARCHAR(45) NULL,
  USER_PHONE VARCHAR(45) NULL,
  USER_EMAIL VARCHAR(45) NULL

);

CREATE TABLE USER_APP (
  USERID integer NOT NULL,
  APPID integer NOT NULL,
  PRIMARY KEY (USERID, APPID),
  FOREIGN KEY (USERID) REFERENCES T_USERS (ID),
  FOREIGN KEY (APPID) REFERENCES T_APP (ID)

 );


CREATE TABLE T_DEPLOY (
  ID integer NOT NULL AUTO_INCREMENT PRIMARY KEY,
  DEP_ID VARCHAR(50) NOT NULL,
  USER_ID integer NOT NULL,
  APP_ID integer NOT NULL,
  DEP_DATE date,
  DEP_ENV VARCHAR(100),
  DEP_STATUS VARCHAR(20),
  DEP_REMARKS VARCHAR(400),
  FOREIGN KEY (USER_ID) REFERENCES T_USERS (ID),
  FOREIGN KEY (APP_ID) REFERENCES T_APP (ID)

 );

 CREATE TABLE T_SVN_DETAIL (
   ID integer NOT NULL AUTO_INCREMENT PRIMARY KEY,
   FILE_NAMES VARCHAR(2000) NOT NULL,
   VERSION VARCHAR(100),
   CHANGED_BY VARCHAR(20),
   DEP_ID integer,
   CHANGE_DATE date,
   FOREIGN KEY (DEP_ID) REFERENCES T_DEPLOY (ID)
  );

   CREATE TABLE T_JIRA_DETAILS (
     ID integer NOT NULL AUTO_INCREMENT PRIMARY KEY,
     JIRA_NO VARCHAR(100) NOT NULL,
     JIRA_DESC VARCHAR(400),
     JIRA_STATUS VARCHAR(20),
     FIX_VERSION VARCHAR(100),
     DEP_ID integer,
     FOREIGN KEY (DEP_ID) REFERENCES T_DEPLOY (ID)
    );

     CREATE TABLE T_SONAR_DETAILS (
         ID integer NOT NULL AUTO_INCREMENT PRIMARY KEY,
         SONAR_ID VARCHAR(100) NOT NULL,
         BLOCKERS integer,
         CRITICALS integer,
         MAJORS integer,
         DEP_ID integer,
         SONAR_DATE date,
         FOREIGN KEY (DEP_ID) REFERENCES T_DEPLOY (ID)
        );




# --- !Downs

DROP TABLE T_APP;

DROP TABLE T_USERS;

DROP TABLE USER_APP;
DROP TABLE T_DEPLOY;
DROP TABLE T_SVN_DETAIL;
DROP TABLE T_JIRA_DETAILS;

