# DC schema

# --- !Ups


CREATE TABLE T_APP (
  ID integer NOT NULL AUTO_INCREMENT PRIMARY KEY,
  C_APPID VARCHAR(45) NULL,
  C_APPNAME VARCHAR(45) NULL,
  C_APPDESC VARCHAR(200) NULL,
  C_APPTYPE VARCHAR(45) NULL,
  C_CONTAINER VARCHAR(45) NULL,
  C_DEPTYPE VARCHAR(45) NULL,
  C_PROJMGR VARCHAR(45) NULL,
  C_PROCESSNAME VARCHAR(45) NULL,
  C_TEAM       VARCHAR(45) NULL,
  C_APPREPO   VARCHAR (45) NULL,
  C_PLAYBOOK  VARCHAR(500) NULL

);

# --- !Downs

DROP TABLE T_APP;